
server:
  port: 8089


spring:
  # Thymeleaf 配置
  thymeleaf:
    prefix: classpath:/templates/   #配置模板路径，默认是templates，可以不用配置
    mode: LEGACYHTML5               # 语法不严格按照HTML5
    cache: false                   #开发配置为false,避免修改模板还要重启服务器  注意 页面修改代码之后，使用 Ctrl + F9
    encoding: UTF-8
    suffix: .html                   #名称的后缀
